version: 2

jobs:
  build:
    working_directory: /loquesea
    docker:
      - image: docker:20.10.13
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=20.3.4-r1
            pip install docker-compose==1.26.2
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerizando python test.py
